TOOLS_LIB=../lib
TOOLS_INCLUDE=../include
BOOST_LIB=/home/nikita/work/ri/extern/BOOST/lib
BOOST_INCLUDE=/home/nikita/work/ri/extern/BOOST/include

all: searcher

searcher:
	g++-8 -std=c++17 -I $(TOOLS_INCLUDE) -I $(BOOST_INCLUDE) make_search.cpp -lstdc++fs -o search 
